hw10/authors/urls.py
from django.urls import path

from . import views

app_name = "authors"

urlpatterns = [
    path('<str:author_id>/', views.main, name="root"),        
    
]

hw10/hw10/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    #під'єднуємо урли цитат
    path("", include("quotes.urls")),
    path("authors/", include("authors.urls")),    
    path("users/", include("users.urls"))   
]

hw10/quotes/urls.py
from django.urls import path

from . import views


app_name = "quotes"

urlpatterns = [
    path('', views.main, name="root"),
    path('<int:page>/', views.main, name="root_paginate"),
    path('add_author/', views.add_author, name='add_author'), 
    path('authors/<int:author_id>/', views.author_details, name="author_details"), #было  name="root"
    path('add_quote/', views.add_quote, name='add_quote'), 
    path('quotes/', views.main, name='quotes'),    
]

hw10/users/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
#from .views import CustomLogoutView

from .forms import LoginForm
from .views import RegisterViews


app_name = "users"

urlpatterns = [
    path('signup/', RegisterViews.as_view(), name="register"), #new4
    path('login/', LoginView.as_view(template_name='users/login.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),    
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),    
]

hw10/authors/models.py
from django.db import models

# Create your models here.

hw10/quotes/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User #new


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
   

    def get_absolute_url(self):
        return reverse_lazy('authors:root', args=[str(self.id)])
    
    def __str__(self):
        return self.fullname

    

class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return self.name

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw10/quotes/forms.py
from django import forms
from .models import Author, Quote, Tag

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)    
        self.fields['tags'].queryset = Tag.objects.all()
    
    def clean_tags(self):        
        return self.cleaned_data['tags']

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

    name = forms.CharField(max_length=100)
    

    def __str__(self):
        return self.name

hw10/authors/views.py
from django.shortcuts import render
from django.http import HttpResponse
from bson import ObjectId

from .utils import get_mongodb



def main(request, author_id):
    try:
        object_id = ObjectId(author_id)
        db = get_mongodb()
        author = db.authors.find_one({'_id': object_id})

        if author:
            return render(request, "authors/index.html", context={'authors': [author]})
        else:
            return HttpResponse(f"Author with ID {author_id} not found.")
    except Exception as e:
        return HttpResponse(f"Invalid author ID format: {e}")
    

hw10/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator 
from .forms import QuoteForm, AuthorForm, TagForm
from .models import Quote, Author  
from django.contrib.auth.decorators import login_required #new 7/3

def main(request, page=1):
    per_page = 10
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, per_page)
    quote_on_page = paginator.page(page)

    author_ids = set(quote.author.id for quote in quote_on_page.object_list)
    
    authors = Author.objects.filter(id__in=author_ids)
    author_dict = {str(author.id): author for author in authors}
    
    for quote in quote_on_page.object_list:
        author_id = str(quote.author.id)
        quote.author_object = author_dict.get(author_id, {})

    return render(request, 'quotes/index.html', context={'quotes': quote_on_page, 'authors': authors})

@login_required
def add_author(request):
    if request.method == 'POST':
        author_form = AuthorForm(request.POST)
        if author_form.is_valid():
            author_form.save()
            return redirect('quotes:root')
    else:
        author_form = AuthorForm()

    return render(request, 'quotes/add_author.html', context={'author_form': author_form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        quote_form = QuoteForm(request.POST)
        if quote_form.is_valid():
            quote_form.save()
            return redirect('quotes:root')
    else:
        quote_form = QuoteForm()

    return render(request, 'quotes/add_quote.html', context={'quote_form': quote_form})

@login_required
def author_details(request, author_id):    
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes/authors.html', context={'author': author}) #index_id

hw10/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

  <h1>Add Author</h1>

  <form method="post" action="{% url 'quotes:add_author' %}">
      {% csrf_token %}
      {{ author_form.as_p }}
      <button type="submit" class="btn btn-primary">Add Author</button>
  </form>

  <div class="row">
      {% for quote in quotes %}
          <div class="col-md-4">
              <div class="card" style="width: 18rem;">
                  
                  <div class="card-body">
                      <h5 class="card-title">Card title</h5>
                      <p class="card-text">{{ quote.quote }}</p>
                      
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>

{% endblock %}

hw10/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

  <h1>Add Quotes</h1>

  <form method="post" action="{% url 'quotes:add_quote' %}">
      {% csrf_token %}
      {{ quote_form.as_p }}
      <button type="submit" class="btn btn-primary">Add Quote</button>
  </form>

  <div class="row">
      {% for quote in quotes %}
          <div class="col-md-4">
              <div class="card" style="width: 18rem;">
                
                  <div class="card-body">
                      <h5 class="card-title">{{ quote.author.fullname }}</h5>
                      <p class="card-text">{{ quote.quote }}</p>
                      <p class="card-text">
                          Tags: {{ quote_form.tags }}
                      </p>
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>

{% endblock %}

hw10/quotes/templates/quotes/authors.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Authors</title>
</head>
<body>

<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>

                <a href="/login">Login</a>

            </p>
        </div>
    </div>


    <div class="author-details">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <p><strong>Дата рождения:</strong> <span class="author-born-date">{{ author.born_date }}</span> 
            <span class="author-born-location">в {{ author.born_location }}</span></p>
        <p><strong>Описание:</strong></p>
        <div class="author-description">
            {{ author.description }}
        </div>
    </div> 


</body>
</html>

hw10/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">

    <title>Document</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated%}
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Logout</button>
                </form>
                {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}                             
                
    </p>

            </p>
        </div>
    </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

hw10/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes%}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>            
                <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small></span>
 
 <a href="{% url 'authors:root' quote.author.id %}">(about)</a>   
    
    </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}             
                <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>                              
                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">
            
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                     href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                
                
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span>
                </a>
                </li>
                
            </ul>
        </nav>
    </div>

</div>

{% endblock %}

hw10/quotes/templates/quotes/index_authors.html
{% extends "quotes/authors.html" %}

{% block content %}

<div class="author-details">
    {% for author in authors %}
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.date_born}}</span> 
        <span class="author-born-location">in {{author.location_born}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.bio}}
    </div>
    
</div>
{% endfor %}
</div>
{% endblock %}